name: build_image_deploy

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: self-hosted
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hi Ravi shankar"
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Read file contents
      id: read_file
      uses: juliangruber/read-file-action@v1.1.6
      with:
        path: "production.json"

    - name: File contents
      run: echo "${{ steps.package.outputs.content }}"
