name: build_image_deploy

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: self-hosted
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hi Ravi shankar"
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Read file contents
      id: read_file
      uses: juliangruber/read-file-action@v1.1.6
      with:
        path: ./production.json

    - name: File contents
      run: |
           echo "${{ steps.read_file.outputs.content }}"
           source activate demo-mlops-new1
           mlflow --version
           mlflow models build-docker -m ./demo_mlops/mlruns/4/316fe7ffd8dc428fbbad7aac1e98a4ba/artifacts/sklearn-model -n sklearn-model
    - name: Deploy the model
      run: |
           docker rm -f demo_mlops
           docker run -itd --name demo_mlops --restart=always -p 8002:8080 sklearn-model
 
 
   
